In [ ]:
# shift + M 셀 병합 commandmode
# 셀 나누기 shift ctrl -   edit mode

# Numpy 사용하기

In [20]:
import numpy as np

# array  생성하기

In [4]:
# 1차원 생성
list1=[1,2,3,4,5]
arr1=np.array(list1)
print(arr1)

[1 2 3 4 5]


In [5]:
# 2차원 생성
list2=[[1,2,3],[4,5,6]]
arr2=np.array(list2)
print(arr2)

[[1 2 3]
 [4 5 6]]


# array 값 확인하기

In [6]:
#배열의 크기 확인하기
#shpate
arr2.shape

(2, 3)

In [7]:
#요소 개수 확인하기
# size
print("요소의 개수 : {}".format(arr2.size))

요소의 개수 : 6


In [9]:
#차원 확인하기
# ndim
print(arr1.ndim)
print(arr2.ndim)

1
2


In [10]:
#타입 확인하기
# dtype
arr2.dtype

dtype('int32')

In [12]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
print("배열의 크기",arr3.shape)
print("배열의 차원",arr3.ndim)
print("배열의 요소 개수",arr3.size)


배열의 크기 (2, 2, 2)
배열의 차원 3
배열의 요소 개수 8


# 특정값으로 배열 생성
-0으로 만들기
np.zeros(배열의크기)

In [19]:
arr_zero=np.zeros((3,4))
print(arr_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 1로 만들기
np.ones()

In [20]:
arr_one=np.ones((5,9))
print(arr_one)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


원하는 값 만들기
np.full(배열의 크기, 채울 값)

In [23]:
arr_full=np.full((4,5),5)
print(arr_full)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


원하는 범위로 만들기

In [38]:
# 1~50 값이 담긴 배열

list=[]
for i in range(1,51):
    list.append(i)
    
arr_range=np.array(list)

In [41]:
print(list)
print()
print(arr_range)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [42]:
arr_2=np.arange(1,51)
print(arr_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


-랜덤값 만들기
-np.random.rand
-np.random.randint


np.random.rand(배열의 크기) : 0~1까지의 랜덤값 사용

np.random.randint(시작하는수, 끝나는 수 다음수, 배열의 크기) 
-시작수~ 끝수까지ㅇ 범위를 갖는 난수 생성

In [5]:
list1=np.random.rand(2,3)
print(list1)

[[0.28927513 0.56083976 0.68665937]
 [0.54751024 0.11075041 0.55177406]]


In [8]:
list2=np.random.randint(2,10,size=(3,5))
print(list2)

[[8 3 6 7 2]
 [8 8 7 2 3]
 [4 9 5 6 8]]


In [12]:
# 배열이 생성된 후 타입 변경
# astype
arr=np.array([1.2,2.3,3.4])
print(arr.dtype)
arr

float64


array([1.2, 2.3, 3.4])

In [14]:
arr=arr.astype("int32")
arr

array([1, 2, 3])

# 배열 연산

#배열끼리의 연산
#배열안에서 연산
#인덱싱, 슬라이싱

In [22]:
#2차원 array
# [[1,2,3],[4,5,6]]
# [[7,8,9],[10,11,12]]

In [17]:
list2=[[1,2,3],[4,5,6]]
arr2=np.array(list2)
print(arr2)
list3=[[7,8,9],[10,11,12]]
arr3=np.array(list3)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [23]:
arr2+arr3

array([[ 8, 10, 12],
       [14, 16, 18]])

In [31]:
#인덱싱
print(arr2.shape)
print(arr2)
print(arr2[0,1])

(2, 3)
[[1 2 3]
 [4 5 6]]
2


In [32]:
arr2[0][1]

2

In [ ]:
#슬라이싱

In [35]:
# 0~9까지 담긴 1차원 array
arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
print(arr[3:7])
#arr[3:7]=10

[3 4 5 6]


In [41]:
#배열 크기 바꾸기 reshape
arr2=np.arange(50).reshape(5,10)
print(arr2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [46]:
#슬라이싱
#[큰차원의 범위, 작은차원의 범위]
print(arr2[:4,3:7])

[[ 3  4  5  6]
 [13 14 15 16]
 [23 24 25 26]
 [33 34 35 36]]


In [49]:
arr2[0:4][2:3]
#자르고 또 자름
# 결과갑이 2차원의 데이터이기때문에 
# arr2[0:4][3:7]이 코드는 1차원에 접근할 수 없다.

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [53]:
data=np.loadtxt("height_weight.txt", delimiter=",")
print(data)


[[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
 [ 65.6  88.   79.2  69.3  55.   71.2  73.   68.9  74.   82. ]]


In [94]:

list=[]
for i in range(0,10):
    list1=(data[1][i])/((data[0][i]/100)*(data[0][i]/100))
    list.append(list1)
print(list)

for i in range(0,10):
    print("%1.2f"%list[i])
print()
for i in range(0,10):
    print("{:1.3f}".format(list[i]))

[21.371531035633122, 27.070184683258837, 25.86122448979592, 24.206528846637497, 16.035434227896758, 20.144861928474423, 23.143920947975, 21.697206508280214, 23.620287912158062, 25.592209980961893]
21.37
27.07
25.86
24.21
16.04
20.14
23.14
21.70
23.62
25.59

21.372
27.070
25.861
24.207
16.035
20.145
23.144
21.697
23.620
25.592


# Boolean 인덱싱
true값 출력,
false값 출력 않음

In [95]:
name=np.array(["예호", "운비", "명훈", "매일"])
print(name)

['예호' '운비' '명훈' '매일']


In [96]:
bol=np.array([True, False, True, False])
bol

array([ True, False,  True, False])

In [97]:
name[bol]

array(['예호', '명훈'], dtype='<U2')

In [100]:
name=np.array(["예호", "운비", "명훈", "매일"])
name_score=np.array([[60,60],[70,70],[80,80],[90,90]])

In [101]:
name_score.shape

(4, 2)

In [109]:
name=="운비"

array([False,  True, False, False])

In [105]:
# bol 데이터는 고정되지 않고
# name=="운비"하면 또 변함
print(name_score[name=="예호"])
print(name_score[name=="운비"])

[[60 60]]
[[70 70]]


# 함수

In [113]:
#1~9까지의 범위를 갖는 랜덤수 배열 (2,5)
list=np.random.randint(1,10,(2,5))
print("list\n",list)

list
 [[4 4 5 7 4]
 [9 8 9 7 2]]


In [110]:
#sum
# 전부 더하기
np.sum(list)

57

In [122]:
#axis
#차원 끼리 연산
print(np.sum(list, axis=0))
print(np.sum(list, axis=1))
print(list.shape)

[13 12 14 14  6]
[24 35]
(2, 5)


In [126]:
#mean 평균
print(np.mean(list))
print(np.mean(list, axis=0))
print(np.mean(list, axis=1))

5.9
[6.5 6.  7.  7.  3. ]
[4.8 7. ]


In [130]:
data=np.loadtxt("ratings.txt", delimiter="::")
data=data.astype("int32")
print(data)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [131]:
data.shape

(1000209, 4)

In [133]:
#전체 평점 평균 구하기
print(np.mean(data[:,2]))

3.581564453029317


In [173]:
# 1번 사용자의 평점 평균 구하기
# boolean 인덱싱
#print(np.mean(data[num==1,:],2))
bol = np.array([True , False, True, False])
num = np.array(data[ : , 0])
score = np.array(data[ : , 2])
print(num)
print(score)
m=np.mean(score[num == 1])
print("{0:1.3f}".format(m))

[   1    1    1 ... 6040 6040 6040]
[5 3 3 ... 5 4 4]
4.189


In [172]:
data[data[:,0]==1,2].mean()

4.188679245283019

In [175]:
# 각 사용자별 평균 평점
# unique
# 중복된 값들 한번만 출력
print(data[:,0])
print(np.unique(data[:,0]))

[   1    1    1 ... 6040 6040 6040]
[   1    2    3 ... 6038 6039 6040]


In [177]:
user_id=np.unique(data[:,0])
for userid in user_id:
    print(userid)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


2566
2567
2568
2569
2570
2571
2572
2573
2574
2575
2576
2577
2578
2579
2580
2581
2582
2583
2584
2585
2586
2587
2588
2589
2590
2591
2592
2593
2594
2595
2596
2597
2598
2599
2600
2601
2602
2603
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2625
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
2636
2637
2638
2639
2640
2641
2642
2643
2644
2645
2646
2647
2648
2649
2650
2651
2652
2653
2654
2655
2656
2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2673
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
2686
2687
2688
2689
2690
2691
2692
2693
2694
2695
2696
2697
2698
2699
2700
2701
2702
2703
2704
2705
2706
2707
2708
2709
2710
2711
2712
2713
2714
2715
2716
2717
2718
2719
2720
2721
2722
2723
2724
2725
2726
2727
2728
2729
2730
2731
2732
2733
2734
2735
2736
2737
2738
2739
2740
2741
2742
2743
2744
2745
2746
2747
2748
2749
2750
2751
2752
2753
2754
2755
2756
2757
2758
2759
2760
2761
2762
2763
2764
2765


5049
5050
5051
5052
5053
5054
5055
5056
5057
5058
5059
5060
5061
5062
5063
5064
5065
5066
5067
5068
5069
5070
5071
5072
5073
5074
5075
5076
5077
5078
5079
5080
5081
5082
5083
5084
5085
5086
5087
5088
5089
5090
5091
5092
5093
5094
5095
5096
5097
5098
5099
5100
5101
5102
5103
5104
5105
5106
5107
5108
5109
5110
5111
5112
5113
5114
5115
5116
5117
5118
5119
5120
5121
5122
5123
5124
5125
5126
5127
5128
5129
5130
5131
5132
5133
5134
5135
5136
5137
5138
5139
5140
5141
5142
5143
5144
5145
5146
5147
5148
5149
5150
5151
5152
5153
5154
5155
5156
5157
5158
5159
5160
5161
5162
5163
5164
5165
5166
5167
5168
5169
5170
5171
5172
5173
5174
5175
5176
5177
5178
5179
5180
5181
5182
5183
5184
5185
5186
5187
5188
5189
5190
5191
5192
5193
5194
5195
5196
5197
5198
5199
5200
5201
5202
5203
5204
5205
5206
5207
5208
5209
5210
5211
5212
5213
5214
5215
5216
5217
5218
5219
5220
5221
5222
5223
5224
5225
5226
5227
5228
5229
5230
5231
5232
5233
5234
5235
5236
5237
5238
5239
5240
5241
5242
5243
5244
5245
5246
5247
5248


In [182]:
user_id.size

6040

In [185]:
user_id=np.unique(data[:,0])
for userid in user_id:
    #print(userid, "번 사용자",data[data[:,0]==userid,2].mean() )
    print(f"{userid}번 사용자의 평균 평점 : %.2f"%data[data[:,0]==userid,2].mean())

1번 사용자의 평균 평점 : 4.19
2번 사용자의 평균 평점 : 3.71
3번 사용자의 평균 평점 : 3.90
4번 사용자의 평균 평점 : 4.19
5번 사용자의 평균 평점 : 3.15
6번 사용자의 평균 평점 : 3.90
7번 사용자의 평균 평점 : 4.32
8번 사용자의 평균 평점 : 3.88
9번 사용자의 평균 평점 : 3.74
10번 사용자의 평균 평점 : 4.11
11번 사용자의 평균 평점 : 3.28
12번 사용자의 평균 평점 : 3.83
13번 사용자의 평균 평점 : 3.39
14번 사용자의 평균 평점 : 3.32
15번 사용자의 평균 평점 : 3.32
16번 사용자의 평균 평점 : 3.03
17번 사용자의 평균 평점 : 4.08
18번 사용자의 평균 평점 : 3.65
19번 사용자의 평균 평점 : 3.57
20번 사용자의 평균 평점 : 4.08
21번 사용자의 평균 평점 : 2.91
22번 사용자의 평균 평점 : 3.07
23번 사용자의 평균 평점 : 3.32
24번 사용자의 평균 평점 : 3.95
25번 사용자의 평균 평점 : 3.74
26번 사용자의 평균 평점 : 2.96
27번 사용자의 평균 평점 : 4.17
28번 사용자의 평균 평점 : 3.76
29번 사용자의 평균 평점 : 3.58
30번 사용자의 평균 평점 : 3.49
31번 사용자의 평균 평점 : 3.73
32번 사용자의 평균 평점 : 3.62
33번 사용자의 평균 평점 : 3.50
34번 사용자의 평균 평점 : 3.87
35번 사용자의 평균 평점 : 3.54
36번 사용자의 평균 평점 : 4.20
37번 사용자의 평균 평점 : 3.70
38번 사용자의 평균 평점 : 3.58
39번 사용자의 평균 평점 : 3.56
40번 사용자의 평균 평점 : 3.45
41번 사용자의 평균 평점 : 3.48
42번 사용자의 평균 평점 : 3.74
43번 사용자의 평균 평점 : 4.12
44번 사용자의 평균 평점 : 3.63
45번 사용자의 평균 평점 : 2.95
46번 사용자의 평균 평점 : 4.

407번 사용자의 평균 평점 : 3.44
408번 사용자의 평균 평점 : 4.35
409번 사용자의 평균 평점 : 3.92
410번 사용자의 평균 평점 : 3.97
411번 사용자의 평균 평점 : 3.28
412번 사용자의 평균 평점 : 4.40
413번 사용자의 평균 평점 : 4.40
414번 사용자의 평균 평점 : 3.07
415번 사용자의 평균 평점 : 3.87
416번 사용자의 평균 평점 : 3.76
417번 사용자의 평균 평점 : 4.05
418번 사용자의 평균 평점 : 3.55
419번 사용자의 평균 평점 : 3.96
420번 사용자의 평균 평점 : 4.36
421번 사용자의 평균 평점 : 4.25
422번 사용자의 평균 평점 : 3.30
423번 사용자의 평균 평점 : 2.50
424번 사용자의 평균 평점 : 3.74
425번 사용자의 평균 평점 : 3.66
426번 사용자의 평균 평점 : 3.76
427번 사용자의 평균 평점 : 4.11
428번 사용자의 평균 평점 : 3.90
429번 사용자의 평균 평점 : 3.35
430번 사용자의 평균 평점 : 3.97
431번 사용자의 평균 평점 : 3.63
432번 사용자의 평균 평점 : 2.99
433번 사용자의 평균 평점 : 3.39
434번 사용자의 평균 평점 : 4.02
435번 사용자의 평균 평점 : 3.83
436번 사용자의 평균 평점 : 3.83
437번 사용자의 평균 평점 : 4.31
438번 사용자의 평균 평점 : 3.53
439번 사용자의 평균 평점 : 3.90
440번 사용자의 평균 평점 : 3.59
441번 사용자의 평균 평점 : 3.96
442번 사용자의 평균 평점 : 3.85
443번 사용자의 평균 평점 : 3.82
444번 사용자의 평균 평점 : 4.00
445번 사용자의 평균 평점 : 3.32
446번 사용자의 평균 평점 : 4.84
447번 사용자의 평균 평점 : 4.84
448번 사용자의 평균 평점 : 3.43
449번 사용자의 평균 평점 : 3.72
450번 사용자의 평

811번 사용자의 평균 평점 : 4.18
812번 사용자의 평균 평점 : 3.74
813번 사용자의 평균 평점 : 3.34
814번 사용자의 평균 평점 : 4.06
815번 사용자의 평균 평점 : 4.07
816번 사용자의 평균 평점 : 3.70
817번 사용자의 평균 평점 : 4.01
818번 사용자의 평균 평점 : 3.73
819번 사용자의 평균 평점 : 3.32
820번 사용자의 평균 평점 : 3.41
821번 사용자의 평균 평점 : 2.95
822번 사용자의 평균 평점 : 3.72
823번 사용자의 평균 평점 : 3.87
824번 사용자의 평균 평점 : 3.65
825번 사용자의 평균 평점 : 3.62
826번 사용자의 평균 평점 : 3.29
827번 사용자의 평균 평점 : 3.95
828번 사용자의 평균 평점 : 3.44
829번 사용자의 평균 평점 : 4.23
830번 사용자의 평균 평점 : 3.61
831번 사용자의 평균 평점 : 4.11
832번 사용자의 평균 평점 : 3.56
833번 사용자의 평균 평점 : 4.05
834번 사용자의 평균 평점 : 4.16
835번 사용자의 평균 평점 : 2.75
836번 사용자의 평균 평점 : 2.40
837번 사용자의 평균 평점 : 3.26
838번 사용자의 평균 평점 : 4.09
839번 사용자의 평균 평점 : 3.99
840번 사용자의 평균 평점 : 4.22
841번 사용자의 평균 평점 : 3.58
842번 사용자의 평균 평점 : 3.84
843번 사용자의 평균 평점 : 3.94
844번 사용자의 평균 평점 : 3.45
845번 사용자의 평균 평점 : 3.98
846번 사용자의 평균 평점 : 3.92
847번 사용자의 평균 평점 : 3.61
848번 사용자의 평균 평점 : 4.18
849번 사용자의 평균 평점 : 3.26
850번 사용자의 평균 평점 : 3.56
851번 사용자의 평균 평점 : 3.59
852번 사용자의 평균 평점 : 4.12
853번 사용자의 평균 평점 : 3.89
854번 사용자의 평

1209번 사용자의 평균 평점 : 3.41
1210번 사용자의 평균 평점 : 3.90
1211번 사용자의 평균 평점 : 3.86
1212번 사용자의 평균 평점 : 3.86
1213번 사용자의 평균 평점 : 4.04
1214번 사용자의 평균 평점 : 3.02
1215번 사용자의 평균 평점 : 4.03
1216번 사용자의 평균 평점 : 3.69
1217번 사용자의 평균 평점 : 4.24
1218번 사용자의 평균 평점 : 3.46
1219번 사용자의 평균 평점 : 3.62
1220번 사용자의 평균 평점 : 3.35
1221번 사용자의 평균 평점 : 3.96
1222번 사용자의 평균 평점 : 3.22
1223번 사용자의 평균 평점 : 3.92
1224번 사용자의 평균 평점 : 4.05
1225번 사용자의 평균 평점 : 4.04
1226번 사용자의 평균 평점 : 3.29
1227번 사용자의 평균 평점 : 3.79
1228번 사용자의 평균 평점 : 3.78
1229번 사용자의 평균 평점 : 4.00
1230번 사용자의 평균 평점 : 3.94
1231번 사용자의 평균 평점 : 3.85
1232번 사용자의 평균 평점 : 4.23
1233번 사용자의 평균 평점 : 3.89
1234번 사용자의 평균 평점 : 4.29
1235번 사용자의 평균 평점 : 3.70
1236번 사용자의 평균 평점 : 3.38
1237번 사용자의 평균 평점 : 3.77
1238번 사용자의 평균 평점 : 3.71
1239번 사용자의 평균 평점 : 3.86
1240번 사용자의 평균 평점 : 3.07
1241번 사용자의 평균 평점 : 4.25
1242번 사용자의 평균 평점 : 3.64
1243번 사용자의 평균 평점 : 3.61
1244번 사용자의 평균 평점 : 3.38
1245번 사용자의 평균 평점 : 4.33
1246번 사용자의 평균 평점 : 3.57
1247번 사용자의 평균 평점 : 3.81
1248번 사용자의 평균 평점 : 3.60
1249번 사용자의 평균 평점 : 3.96
1250번 사용자의 평균 평점

1556번 사용자의 평균 평점 : 3.21
1557번 사용자의 평균 평점 : 3.98
1558번 사용자의 평균 평점 : 4.12
1559번 사용자의 평균 평점 : 3.59
1560번 사용자의 평균 평점 : 3.49
1561번 사용자의 평균 평점 : 4.01
1562번 사용자의 평균 평점 : 2.87
1563번 사용자의 평균 평점 : 3.81
1564번 사용자의 평균 평점 : 3.06
1565번 사용자의 평균 평점 : 3.74
1566번 사용자의 평균 평점 : 3.50
1567번 사용자의 평균 평점 : 3.89
1568번 사용자의 평균 평점 : 4.00
1569번 사용자의 평균 평점 : 4.59
1570번 사용자의 평균 평점 : 3.55
1571번 사용자의 평균 평점 : 3.95
1572번 사용자의 평균 평점 : 3.18
1573번 사용자의 평균 평점 : 3.69
1574번 사용자의 평균 평점 : 3.60
1575번 사용자의 평균 평점 : 3.87
1576번 사용자의 평균 평점 : 3.88
1577번 사용자의 평균 평점 : 4.10
1578번 사용자의 평균 평점 : 4.16
1579번 사용자의 평균 평점 : 3.45
1580번 사용자의 평균 평점 : 3.54
1581번 사용자의 평균 평점 : 3.22
1582번 사용자의 평균 평점 : 3.64
1583번 사용자의 평균 평점 : 3.73
1584번 사용자의 평균 평점 : 3.33
1585번 사용자의 평균 평점 : 3.61
1586번 사용자의 평균 평점 : 4.42
1587번 사용자의 평균 평점 : 3.33
1588번 사용자의 평균 평점 : 4.17
1589번 사용자의 평균 평점 : 3.78
1590번 사용자의 평균 평점 : 4.00
1591번 사용자의 평균 평점 : 4.34
1592번 사용자의 평균 평점 : 3.62
1593번 사용자의 평균 평점 : 3.04
1594번 사용자의 평균 평점 : 3.73
1595번 사용자의 평균 평점 : 4.05
1596번 사용자의 평균 평점 : 3.57
1597번 사용자의 평균 평점

1899번 사용자의 평균 평점 : 3.79
1900번 사용자의 평균 평점 : 3.67
1901번 사용자의 평균 평점 : 4.17
1902번 사용자의 평균 평점 : 3.65
1903번 사용자의 평균 평점 : 4.02
1904번 사용자의 평균 평점 : 3.27
1905번 사용자의 평균 평점 : 4.11
1906번 사용자의 평균 평점 : 3.65
1907번 사용자의 평균 평점 : 3.83
1908번 사용자의 평균 평점 : 3.18
1909번 사용자의 평균 평점 : 3.53
1910번 사용자의 평균 평점 : 3.64
1911번 사용자의 평균 평점 : 3.55
1912번 사용자의 평균 평점 : 2.49
1913번 사용자의 평균 평점 : 4.30
1914번 사용자의 평균 평점 : 3.74
1915번 사용자의 평균 평점 : 3.61
1916번 사용자의 평균 평점 : 3.94
1917번 사용자의 평균 평점 : 3.90
1918번 사용자의 평균 평점 : 3.00
1919번 사용자의 평균 평점 : 3.56
1920번 사용자의 평균 평점 : 3.39
1921번 사용자의 평균 평점 : 3.26
1922번 사용자의 평균 평점 : 3.46
1923번 사용자의 평균 평점 : 3.28
1924번 사용자의 평균 평점 : 3.15
1925번 사용자의 평균 평점 : 3.65
1926번 사용자의 평균 평점 : 4.09
1927번 사용자의 평균 평점 : 3.95
1928번 사용자의 평균 평점 : 3.84
1929번 사용자의 평균 평점 : 3.56
1930번 사용자의 평균 평점 : 3.17
1931번 사용자의 평균 평점 : 3.62
1932번 사용자의 평균 평점 : 3.67
1933번 사용자의 평균 평점 : 3.47
1934번 사용자의 평균 평점 : 3.08
1935번 사용자의 평균 평점 : 3.48
1936번 사용자의 평균 평점 : 3.71
1937번 사용자의 평균 평점 : 3.18
1938번 사용자의 평균 평점 : 3.13
1939번 사용자의 평균 평점 : 3.78
1940번 사용자의 평균 평점

2243번 사용자의 평균 평점 : 4.68
2244번 사용자의 평균 평점 : 3.40
2245번 사용자의 평균 평점 : 3.10
2246번 사용자의 평균 평점 : 3.67
2247번 사용자의 평균 평점 : 3.92
2248번 사용자의 평균 평점 : 3.75
2249번 사용자의 평균 평점 : 3.93
2250번 사용자의 평균 평점 : 3.07
2251번 사용자의 평균 평점 : 3.66
2252번 사용자의 평균 평점 : 3.48
2253번 사용자의 평균 평점 : 4.10
2254번 사용자의 평균 평점 : 3.96
2255번 사용자의 평균 평점 : 3.67
2256번 사용자의 평균 평점 : 4.00
2257번 사용자의 평균 평점 : 3.54
2258번 사용자의 평균 평점 : 3.45
2259번 사용자의 평균 평점 : 4.47
2260번 사용자의 평균 평점 : 3.64
2261번 사용자의 평균 평점 : 3.40
2262번 사용자의 평균 평점 : 3.68
2263번 사용자의 평균 평점 : 3.71
2264번 사용자의 평균 평점 : 3.63
2265번 사용자의 평균 평점 : 3.64
2266번 사용자의 평균 평점 : 4.05
2267번 사용자의 평균 평점 : 3.55
2268번 사용자의 평균 평점 : 4.26
2269번 사용자의 평균 평점 : 3.36
2270번 사용자의 평균 평점 : 3.45
2271번 사용자의 평균 평점 : 4.11
2272번 사용자의 평균 평점 : 3.92
2273번 사용자의 평균 평점 : 3.85
2274번 사용자의 평균 평점 : 3.77
2275번 사용자의 평균 평점 : 3.86
2276번 사용자의 평균 평점 : 4.32
2277번 사용자의 평균 평점 : 3.39
2278번 사용자의 평균 평점 : 3.42
2279번 사용자의 평균 평점 : 3.64
2280번 사용자의 평균 평점 : 4.11
2281번 사용자의 평균 평점 : 4.05
2282번 사용자의 평균 평점 : 4.03
2283번 사용자의 평균 평점 : 3.70
2284번 사용자의 평균 평점

2648번 사용자의 평균 평점 : 3.94
2649번 사용자의 평균 평점 : 3.15
2650번 사용자의 평균 평점 : 3.73
2651번 사용자의 평균 평점 : 3.31
2652번 사용자의 평균 평점 : 4.05
2653번 사용자의 평균 평점 : 3.62
2654번 사용자의 평균 평점 : 4.08
2655번 사용자의 평균 평점 : 3.13
2656번 사용자의 평균 평점 : 4.09
2657번 사용자의 평균 평점 : 4.05
2658번 사용자의 평균 평점 : 3.90
2659번 사용자의 평균 평점 : 4.11
2660번 사용자의 평균 평점 : 3.68
2661번 사용자의 평균 평점 : 3.61
2662번 사용자의 평균 평점 : 3.69
2663번 사용자의 평균 평점 : 3.69
2664번 사용자의 평균 평점 : 3.45
2665번 사용자의 평균 평점 : 3.07
2666번 사용자의 평균 평점 : 3.87
2667번 사용자의 평균 평점 : 3.41
2668번 사용자의 평균 평점 : 3.42
2669번 사용자의 평균 평점 : 3.75
2670번 사용자의 평균 평점 : 3.55
2671번 사용자의 평균 평점 : 3.22
2672번 사용자의 평균 평점 : 3.63
2673번 사용자의 평균 평점 : 3.75
2674번 사용자의 평균 평점 : 4.14
2675번 사용자의 평균 평점 : 3.32
2676번 사용자의 평균 평점 : 4.17
2677번 사용자의 평균 평점 : 3.71
2678번 사용자의 평균 평점 : 3.90
2679번 사용자의 평균 평점 : 3.78
2680번 사용자의 평균 평점 : 3.29
2681번 사용자의 평균 평점 : 3.63
2682번 사용자의 평균 평점 : 2.70
2683번 사용자의 평균 평점 : 4.37
2684번 사용자의 평균 평점 : 3.53
2685번 사용자의 평균 평점 : 3.60
2686번 사용자의 평균 평점 : 2.81
2687번 사용자의 평균 평점 : 4.26
2688번 사용자의 평균 평점 : 3.47
2689번 사용자의 평균 평점

3044번 사용자의 평균 평점 : 4.02
3045번 사용자의 평균 평점 : 4.28
3046번 사용자의 평균 평점 : 3.34
3047번 사용자의 평균 평점 : 3.64
3048번 사용자의 평균 평점 : 3.91
3049번 사용자의 평균 평점 : 4.27
3050번 사용자의 평균 평점 : 3.66
3051번 사용자의 평균 평점 : 3.26
3052번 사용자의 평균 평점 : 3.22
3053번 사용자의 평균 평점 : 3.25
3054번 사용자의 평균 평점 : 3.51
3055번 사용자의 평균 평점 : 3.51
3056번 사용자의 평균 평점 : 3.65
3057번 사용자의 평균 평점 : 3.47
3058번 사용자의 평균 평점 : 3.70
3059번 사용자의 평균 평점 : 4.00
3060번 사용자의 평균 평점 : 3.57
3061번 사용자의 평균 평점 : 4.12
3062번 사용자의 평균 평점 : 3.30
3063번 사용자의 평균 평점 : 3.69
3064번 사용자의 평균 평점 : 4.20
3065번 사용자의 평균 평점 : 3.79
3066번 사용자의 평균 평점 : 3.93
3067번 사용자의 평균 평점 : 3.75
3068번 사용자의 평균 평점 : 3.76
3069번 사용자의 평균 평점 : 2.88
3070번 사용자의 평균 평점 : 3.92
3071번 사용자의 평균 평점 : 3.08
3072번 사용자의 평균 평점 : 3.38
3073번 사용자의 평균 평점 : 4.54
3074번 사용자의 평균 평점 : 4.30
3075번 사용자의 평균 평점 : 3.63
3076번 사용자의 평균 평점 : 3.82
3077번 사용자의 평균 평점 : 3.85
3078번 사용자의 평균 평점 : 4.06
3079번 사용자의 평균 평점 : 3.88
3080번 사용자의 평균 평점 : 3.88
3081번 사용자의 평균 평점 : 4.04
3082번 사용자의 평균 평점 : 3.37
3083번 사용자의 평균 평점 : 3.85
3084번 사용자의 평균 평점 : 3.71
3085번 사용자의 평균 평점

3389번 사용자의 평균 평점 : 2.83
3390번 사용자의 평균 평점 : 4.19
3391번 사용자의 평균 평점 : 3.72
3392번 사용자의 평균 평점 : 3.80
3393번 사용자의 평균 평점 : 3.54
3394번 사용자의 평균 평점 : 3.89
3395번 사용자의 평균 평점 : 3.70
3396번 사용자의 평균 평점 : 3.83
3397번 사용자의 평균 평점 : 4.07
3398번 사용자의 평균 평점 : 3.60
3399번 사용자의 평균 평점 : 3.55
3400번 사용자의 평균 평점 : 4.06
3401번 사용자의 평균 평점 : 2.95
3402번 사용자의 평균 평점 : 3.84
3403번 사용자의 평균 평점 : 4.14
3404번 사용자의 평균 평점 : 3.81
3405번 사용자의 평균 평점 : 4.12
3406번 사용자의 평균 평점 : 4.05
3407번 사용자의 평균 평점 : 3.50
3408번 사용자의 평균 평점 : 3.77
3409번 사용자의 평균 평점 : 4.20
3410번 사용자의 평균 평점 : 3.22
3411번 사용자의 평균 평점 : 2.73
3412번 사용자의 평균 평점 : 4.16
3413번 사용자의 평균 평점 : 4.11
3414번 사용자의 평균 평점 : 4.10
3415번 사용자의 평균 평점 : 4.01
3416번 사용자의 평균 평점 : 3.58
3417번 사용자의 평균 평점 : 3.87
3418번 사용자의 평균 평점 : 3.79
3419번 사용자의 평균 평점 : 4.03
3420번 사용자의 평균 평점 : 4.35
3421번 사용자의 평균 평점 : 4.33
3422번 사용자의 평균 평점 : 2.66
3423번 사용자의 평균 평점 : 3.94
3424번 사용자의 평균 평점 : 4.20
3425번 사용자의 평균 평점 : 3.54
3426번 사용자의 평균 평점 : 3.98
3427번 사용자의 평균 평점 : 3.76
3428번 사용자의 평균 평점 : 4.00
3429번 사용자의 평균 평점 : 3.60
3430번 사용자의 평균 평점

3740번 사용자의 평균 평점 : 4.28
3741번 사용자의 평균 평점 : 3.61
3742번 사용자의 평균 평점 : 3.71
3743번 사용자의 평균 평점 : 3.56
3744번 사용자의 평균 평점 : 4.08
3745번 사용자의 평균 평점 : 3.30
3746번 사용자의 평균 평점 : 3.79
3747번 사용자의 평균 평점 : 4.03
3748번 사용자의 평균 평점 : 3.72
3749번 사용자의 평균 평점 : 3.69
3750번 사용자의 평균 평점 : 3.44
3751번 사용자의 평균 평점 : 3.39
3752번 사용자의 평균 평점 : 3.37
3753번 사용자의 평균 평점 : 3.78
3754번 사용자의 평균 평점 : 3.69
3755번 사용자의 평균 평점 : 4.47
3756번 사용자의 평균 평점 : 3.87
3757번 사용자의 평균 평점 : 4.26
3758번 사용자의 평균 평점 : 3.14
3759번 사용자의 평균 평점 : 4.01
3760번 사용자의 평균 평점 : 3.78
3761번 사용자의 평균 평점 : 4.19
3762번 사용자의 평균 평점 : 2.54
3763번 사용자의 평균 평점 : 3.89
3764번 사용자의 평균 평점 : 3.93
3765번 사용자의 평균 평점 : 4.00
3766번 사용자의 평균 평점 : 3.05
3767번 사용자의 평균 평점 : 3.20
3768번 사용자의 평균 평점 : 3.36
3769번 사용자의 평균 평점 : 4.29
3770번 사용자의 평균 평점 : 4.00
3771번 사용자의 평균 평점 : 2.68
3772번 사용자의 평균 평점 : 3.85
3773번 사용자의 평균 평점 : 3.43
3774번 사용자의 평균 평점 : 4.00
3775번 사용자의 평균 평점 : 3.81
3776번 사용자의 평균 평점 : 3.90
3777번 사용자의 평균 평점 : 3.63
3778번 사용자의 평균 평점 : 2.69
3779번 사용자의 평균 평점 : 3.62
3780번 사용자의 평균 평점 : 4.24
3781번 사용자의 평균 평점

4090번 사용자의 평균 평점 : 3.81
4091번 사용자의 평균 평점 : 3.45
4092번 사용자의 평균 평점 : 4.15
4093번 사용자의 평균 평점 : 4.34
4094번 사용자의 평균 평점 : 4.17
4095번 사용자의 평균 평점 : 3.79
4096번 사용자의 평균 평점 : 3.34
4097번 사용자의 평균 평점 : 3.73
4098번 사용자의 평균 평점 : 3.86
4099번 사용자의 평균 평점 : 3.74
4100번 사용자의 평균 평점 : 4.14
4101번 사용자의 평균 평점 : 3.63
4102번 사용자의 평균 평점 : 2.79
4103번 사용자의 평균 평점 : 3.50
4104번 사용자의 평균 평점 : 3.53
4105번 사용자의 평균 평점 : 2.73
4106번 사용자의 평균 평점 : 3.00
4107번 사용자의 평균 평점 : 4.02
4108번 사용자의 평균 평점 : 4.34
4109번 사용자의 평균 평점 : 3.48
4110번 사용자의 평균 평점 : 4.33
4111번 사용자의 평균 평점 : 3.64
4112번 사용자의 평균 평점 : 4.04
4113번 사용자의 평균 평점 : 3.52
4114번 사용자의 평균 평점 : 3.80
4115번 사용자의 평균 평점 : 3.81
4116번 사용자의 평균 평점 : 3.79
4117번 사용자의 평균 평점 : 4.09
4118번 사용자의 평균 평점 : 4.06
4119번 사용자의 평균 평점 : 3.54
4120번 사용자의 평균 평점 : 3.38
4121번 사용자의 평균 평점 : 3.88
4122번 사용자의 평균 평점 : 3.54
4123번 사용자의 평균 평점 : 3.31
4124번 사용자의 평균 평점 : 3.42
4125번 사용자의 평균 평점 : 2.80
4126번 사용자의 평균 평점 : 3.51
4127번 사용자의 평균 평점 : 3.84
4128번 사용자의 평균 평점 : 4.00
4129번 사용자의 평균 평점 : 4.00
4130번 사용자의 평균 평점 : 3.68
4131번 사용자의 평균 평점

4490번 사용자의 평균 평점 : 3.51
4491번 사용자의 평균 평점 : 3.80
4492번 사용자의 평균 평점 : 3.91
4493번 사용자의 평균 평점 : 2.34
4494번 사용자의 평균 평점 : 4.20
4495번 사용자의 평균 평점 : 4.14
4496번 사용자의 평균 평점 : 3.82
4497번 사용자의 평균 평점 : 3.78
4498번 사용자의 평균 평점 : 3.07
4499번 사용자의 평균 평점 : 4.03
4500번 사용자의 평균 평점 : 2.96
4501번 사용자의 평균 평점 : 3.97
4502번 사용자의 평균 평점 : 3.90
4503번 사용자의 평균 평점 : 4.16
4504번 사용자의 평균 평점 : 4.12
4505번 사용자의 평균 평점 : 4.21
4506번 사용자의 평균 평점 : 3.96
4507번 사용자의 평균 평점 : 4.37
4508번 사용자의 평균 평점 : 3.08
4509번 사용자의 평균 평점 : 3.92
4510번 사용자의 평균 평점 : 2.84
4511번 사용자의 평균 평점 : 4.18
4512번 사용자의 평균 평점 : 3.86
4513번 사용자의 평균 평점 : 3.77
4514번 사용자의 평균 평점 : 3.37
4515번 사용자의 평균 평점 : 4.41
4516번 사용자의 평균 평점 : 4.38
4517번 사용자의 평균 평점 : 3.07
4518번 사용자의 평균 평점 : 4.55
4519번 사용자의 평균 평점 : 3.67
4520번 사용자의 평균 평점 : 3.77
4521번 사용자의 평균 평점 : 3.80
4522번 사용자의 평균 평점 : 3.40
4523번 사용자의 평균 평점 : 3.46
4524번 사용자의 평균 평점 : 3.30
4525번 사용자의 평균 평점 : 3.95
4526번 사용자의 평균 평점 : 3.62
4527번 사용자의 평균 평점 : 3.80
4528번 사용자의 평균 평점 : 3.31
4529번 사용자의 평균 평점 : 3.85
4530번 사용자의 평균 평점 : 3.61
4531번 사용자의 평균 평점

4839번 사용자의 평균 평점 : 3.04
4840번 사용자의 평균 평점 : 3.74
4841번 사용자의 평균 평점 : 3.64
4842번 사용자의 평균 평점 : 4.00
4843번 사용자의 평균 평점 : 4.07
4844번 사용자의 평균 평점 : 3.97
4845번 사용자의 평균 평점 : 3.94
4846번 사용자의 평균 평점 : 3.50
4847번 사용자의 평균 평점 : 4.01
4848번 사용자의 평균 평점 : 3.85
4849번 사용자의 평균 평점 : 3.99
4850번 사용자의 평균 평점 : 4.00
4851번 사용자의 평균 평점 : 3.67
4852번 사용자의 평균 평점 : 3.76
4853번 사용자의 평균 평점 : 4.11
4854번 사용자의 평균 평점 : 3.80
4855번 사용자의 평균 평점 : 3.02
4856번 사용자의 평균 평점 : 3.75
4857번 사용자의 평균 평점 : 3.26
4858번 사용자의 평균 평점 : 4.04
4859번 사용자의 평균 평점 : 4.23
4860번 사용자의 평균 평점 : 3.90
4861번 사용자의 평균 평점 : 3.84
4862번 사용자의 평균 평점 : 3.48
4863번 사용자의 평균 평점 : 3.58
4864번 사용자의 평균 평점 : 4.18
4865번 사용자의 평균 평점 : 3.38
4866번 사용자의 평균 평점 : 4.03
4867번 사용자의 평균 평점 : 3.82
4868번 사용자의 평균 평점 : 3.71
4869번 사용자의 평균 평점 : 3.33
4870번 사용자의 평균 평점 : 3.69
4871번 사용자의 평균 평점 : 4.00
4872번 사용자의 평균 평점 : 3.54
4873번 사용자의 평균 평점 : 4.21
4874번 사용자의 평균 평점 : 4.39
4875번 사용자의 평균 평점 : 3.93
4876번 사용자의 평균 평점 : 4.06
4877번 사용자의 평균 평점 : 3.72
4878번 사용자의 평균 평점 : 3.60
4879번 사용자의 평균 평점 : 3.46
4880번 사용자의 평균 평점

5184번 사용자의 평균 평점 : 3.91
5185번 사용자의 평균 평점 : 3.29
5186번 사용자의 평균 평점 : 3.71
5187번 사용자의 평균 평점 : 3.54
5188번 사용자의 평균 평점 : 3.87
5189번 사용자의 평균 평점 : 3.62
5190번 사용자의 평균 평점 : 3.93
5191번 사용자의 평균 평점 : 3.67
5192번 사용자의 평균 평점 : 3.68
5193번 사용자의 평균 평점 : 3.69
5194번 사용자의 평균 평점 : 3.42
5195번 사용자의 평균 평점 : 4.24
5196번 사용자의 평균 평점 : 3.15
5197번 사용자의 평균 평점 : 3.54
5198번 사용자의 평균 평점 : 2.96
5199번 사용자의 평균 평점 : 3.46
5200번 사용자의 평균 평점 : 3.98
5201번 사용자의 평균 평점 : 3.42
5202번 사용자의 평균 평점 : 3.38
5203번 사용자의 평균 평점 : 3.97
5204번 사용자의 평균 평점 : 4.06
5205번 사용자의 평균 평점 : 3.35
5206번 사용자의 평균 평점 : 4.00
5207번 사용자의 평균 평점 : 3.86
5208번 사용자의 평균 평점 : 4.06
5209번 사용자의 평균 평점 : 3.95
5210번 사용자의 평균 평점 : 3.80
5211번 사용자의 평균 평점 : 3.72
5212번 사용자의 평균 평점 : 4.55
5213번 사용자의 평균 평점 : 3.34
5214번 사용자의 평균 평점 : 2.42
5215번 사용자의 평균 평점 : 4.40
5216번 사용자의 평균 평점 : 3.30
5217번 사용자의 평균 평점 : 3.35
5218번 사용자의 평균 평점 : 4.16
5219번 사용자의 평균 평점 : 3.94
5220번 사용자의 평균 평점 : 3.35
5221번 사용자의 평균 평점 : 4.17
5222번 사용자의 평균 평점 : 3.15
5223번 사용자의 평균 평점 : 3.33
5224번 사용자의 평균 평점 : 2.94
5225번 사용자의 평균 평점

5528번 사용자의 평균 평점 : 4.40
5529번 사용자의 평균 평점 : 4.29
5530번 사용자의 평균 평점 : 3.02
5531번 사용자의 평균 평점 : 3.86
5532번 사용자의 평균 평점 : 3.42
5533번 사용자의 평균 평점 : 4.00
5534번 사용자의 평균 평점 : 4.18
5535번 사용자의 평균 평점 : 3.60
5536번 사용자의 평균 평점 : 2.91
5537번 사용자의 평균 평점 : 4.39
5538번 사용자의 평균 평점 : 3.88
5539번 사용자의 평균 평점 : 3.75
5540번 사용자의 평균 평점 : 3.81
5541번 사용자의 평균 평점 : 4.07
5542번 사용자의 평균 평점 : 4.66
5543번 사용자의 평균 평점 : 3.59
5544번 사용자의 평균 평점 : 3.57
5545번 사용자의 평균 평점 : 4.34
5546번 사용자의 평균 평점 : 3.47
5547번 사용자의 평균 평점 : 3.59
5548번 사용자의 평균 평점 : 3.45
5549번 사용자의 평균 평점 : 3.52
5550번 사용자의 평균 평점 : 3.65
5551번 사용자의 평균 평점 : 3.14
5552번 사용자의 평균 평점 : 3.15
5553번 사용자의 평균 평점 : 3.63
5554번 사용자의 평균 평점 : 3.67
5555번 사용자의 평균 평점 : 3.11
5556번 사용자의 평균 평점 : 3.28
5557번 사용자의 평균 평점 : 4.21
5558번 사용자의 평균 평점 : 2.45
5559번 사용자의 평균 평점 : 4.18
5560번 사용자의 평균 평점 : 4.17
5561번 사용자의 평균 평점 : 2.92
5562번 사용자의 평균 평점 : 3.51
5563번 사용자의 평균 평점 : 3.58
5564번 사용자의 평균 평점 : 3.20
5565번 사용자의 평균 평점 : 3.98
5566번 사용자의 평균 평점 : 3.87
5567번 사용자의 평균 평점 : 3.42
5568번 사용자의 평균 평점 : 4.04
5569번 사용자의 평균 평점

5874번 사용자의 평균 평점 : 3.55
5875번 사용자의 평균 평점 : 3.83
5876번 사용자의 평균 평점 : 3.83
5877번 사용자의 평균 평점 : 3.68
5878번 사용자의 평균 평점 : 3.63
5879번 사용자의 평균 평점 : 3.78
5880번 사용자의 평균 평점 : 3.21
5881번 사용자의 평균 평점 : 3.57
5882번 사용자의 평균 평점 : 3.70
5883번 사용자의 평균 평점 : 3.35
5884번 사용자의 평균 평점 : 3.88
5885번 사용자의 평균 평점 : 4.08
5886번 사용자의 평균 평점 : 3.27
5887번 사용자의 평균 평점 : 3.65
5888번 사용자의 평균 평점 : 3.18
5889번 사용자의 평균 평점 : 3.91
5890번 사용자의 평균 평점 : 3.91
5891번 사용자의 평균 평점 : 3.67
5892번 사용자의 평균 평점 : 4.09
5893번 사용자의 평균 평점 : 3.17
5894번 사용자의 평균 평점 : 3.90
5895번 사용자의 평균 평점 : 3.50
5896번 사용자의 평균 평점 : 2.55
5897번 사용자의 평균 평점 : 3.89
5898번 사용자의 평균 평점 : 3.76
5899번 사용자의 평균 평점 : 3.38
5900번 사용자의 평균 평점 : 3.30
5901번 사용자의 평균 평점 : 3.20
5902번 사용자의 평균 평점 : 3.63
5903번 사용자의 평균 평점 : 3.77
5904번 사용자의 평균 평점 : 3.50
5905번 사용자의 평균 평점 : 3.64
5906번 사용자의 평균 평점 : 3.92
5907번 사용자의 평균 평점 : 3.85
5908번 사용자의 평균 평점 : 4.12
5909번 사용자의 평균 평점 : 3.28
5910번 사용자의 평균 평점 : 3.78
5911번 사용자의 평균 평점 : 3.84
5912번 사용자의 평균 평점 : 3.59
5913번 사용자의 평균 평점 : 3.87
5914번 사용자의 평균 평점 : 3.94
5915번 사용자의 평균 평점